--
-- PostgreSQL database dump
--

\restrict Om848Xbkn2gFPg28RHIRzVREn1cfyJiJ6XdBMVALJ3xzAS6CwgJKLaIpN4JZRLg

-- Dumped from database version 18.1 (Postgres.app)
-- Dumped by pg_dump version 18.0

-- Started on 2025-12-30 21:46:34 +03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16525)
-- Name: service_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_requests (
    id bigint CONSTRAINT "ServiceRequests_Id_not_null" NOT NULL,
    tracking_code character varying(32) CONSTRAINT "ServiceRequests_TrackingCode_not_null" NOT NULL,
    customer_name character varying(120) CONSTRAINT "ServiceRequests_CustomerName_not_null" NOT NULL,
    customer_phone character varying(30) CONSTRAINT "ServiceRequests_CustomerPhone_not_null" NOT NULL,
    device_name character varying(120) CONSTRAINT "ServiceRequests_DeviceName_not_null" NOT NULL,
    issue_description text CONSTRAINT "ServiceRequests_IssueDescription_not_null" NOT NULL,
    status smallint DEFAULT 0 CONSTRAINT "ServiceRequests_Status_not_null" NOT NULL,
    assigned_technician_id bigint,
    created_by_user_id bigint CONSTRAINT "ServiceRequests_CreatedByUserId_not_null" NOT NULL,
    created_at timestamp with time zone CONSTRAINT "ServiceRequests_CreatedAt_not_null" NOT NULL,
    updated_at timestamp with time zone CONSTRAINT "ServiceRequests_UpdatedAt_not_null" NOT NULL,
    CONSTRAINT chk_service_status CHECK ((status = ANY (ARRAY[0, 1, 2, 3])))
);


ALTER TABLE public.service_requests OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16524)
-- Name: ServiceRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiceRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16544)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint CONSTRAINT "Users_Id_not_null" NOT NULL,
    username character varying(50) CONSTRAINT "Users_Username_not_null" NOT NULL,
    password_hash text CONSTRAINT "Users_PasswordHash_not_null" NOT NULL,
    role character varying(20) CONSTRAINT "Users_Role_not_null" NOT NULL,
    created_at timestamp with time zone CONSTRAINT "Users_CreatedAt_not_null" NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16543)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3833 (class 0 OID 16525)
-- Dependencies: 220
-- Data for Name: service_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_requests (id, tracking_code, customer_name, customer_phone, device_name, issue_description, status, assigned_technician_id, created_by_user_id, created_at, updated_at) FROM stdin;
9	8B1BFDA18C324CDE88A9D3E9ADFED744	sarp yilmaz	5071318459	iphone12	cami kirildiasdasd	0	3	2	2025-12-30 18:59:04.50697+03	2025-12-30 20:17:30.783259+03
10	51FB8B38D2024F60AEE0C2C81A926080	murti	5071318459	iphone13	sdfsdfsdfsdfsdfsdf	0	3	2	2025-12-30 21:15:22.41612+03	2025-12-30 21:15:56.642908+03
\.


--
-- TOC entry 3835 (class 0 OID 16544)
-- Dependencies: 222
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password_hash, role, created_at) FROM stdin;
1	admin@gmail.com	1CEB216DF980C5D920D192DBA1888965357BC76EAF5E463390C9B426B08B9F81	Admin	2025-12-30 13:31:26.915529+03
2	merve@gmail.com	A09B7A160DCF0AC4E5D9A58393CB1C0F3237D9BE74EE09FD9B38158C7577C92A	Clerk	2025-12-30 13:31:26.915529+03
3	murat@gmail.com	A09B7A160DCF0AC4E5D9A58393CB1C0F3237D9BE74EE09FD9B38158C7577C92A	Technician	2025-12-30 13:31:26.915529+03
\.


--
-- TOC entry 3841 (class 0 OID 0)
-- Dependencies: 219
-- Name: ServiceRequests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ServiceRequests_Id_seq"', 10, true);


--
-- TOC entry 3842 (class 0 OID 0)
-- Dependencies: 221
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 3, true);


--
-- TOC entry 3679 (class 2606 OID 16541)
-- Name: service_requests PK_ServiceRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT "PK_ServiceRequests" PRIMARY KEY (id);


--
-- TOC entry 3682 (class 2606 OID 16555)
-- Name: users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_Users" PRIMARY KEY (id);


--
-- TOC entry 3677 (class 1259 OID 16559)
-- Name: IX_ServiceRequests_TrackingCode; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ServiceRequests_TrackingCode" ON public.service_requests USING btree (tracking_code);


--
-- TOC entry 3680 (class 1259 OID 16556)
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public.users USING btree (username);


--
-- TOC entry 3683 (class 2606 OID 16581)
-- Name: service_requests fk_service_requests_assigned_technician; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT fk_service_requests_assigned_technician FOREIGN KEY (assigned_technician_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 3684 (class 2606 OID 16569)
-- Name: service_requests fk_service_requests_created_by_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT fk_service_requests_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


-- Completed on 2025-12-30 21:46:34 +03

--
-- PostgreSQL database dump complete
--

\unrestrict Om848Xbkn2gFPg28RHIRzVREn1cfyJiJ6XdBMVALJ3xzAS6CwgJKLaIpN4JZRLg

